# Generated by Django 6.0.3 on 2026-03-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('dawn', 'Dawn'), ('dusk', 'Dusk'), ('midnight', 'Midnight')], default='dusk', max_length=20),
        ),
    ]
