# Generated by Django 6.0.3 on 2026-03-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('accounting', 'Accounting')], default='cashier', max_length=20),
        ),
    ]
