# Generated by Django 6.0.3 on 2026-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_theme_preference_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('dawn', 'Dawn (Light)'), ('dusk', 'Dusk (Dark)'), ('midnight', 'Midnight (AMOLED)')], default='dusk', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('accounting', 'Accounting')], default='cashier', max_length=20),
        ),
    ]
