# Generated by Django 6.0.3 on 2026-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_theme_preference_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terminal_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
