# Generated by Django 6.0.3 on 2026-03-25 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_terminal_pin'),
        ('sales', '0010_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_daily_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_customer',
            field=models.ForeignKey(blank=True, help_text='Links this user to a customer profile for internal debt tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
