# Generated by Django 6.0.3 on 2026-03-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
    ]
