# Generated by Django 6.0.3 on 2026-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
