# Generated by Django 6.0.3 on 2026-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.FloatField(),
        ),
    ]
