"""Swap LoanPayment to DebtPayment

Revision ID: 97c5f00570bf
Revises: 
Create Date: 2026-03-07 12:44:42.822298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c5f00570bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_payments')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(10)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(10)'))

    op.create_table('loan_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
