# Generated by Django 6.0.3 on 2026-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auditlog_branchvault_shift_vaulttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='closing_cash',
        ),
        migrations.RemoveField(
            model_name='vaulttransaction',
            name='reason',
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_cash',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vaulttransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaulttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('shift_drop', 'Shift Drop'), ('manager_deposit', 'Manager Deposit'), ('manager_withdrawal', 'Manager Withdrawal'), ('audit_adjustment', 'Audit Adjustment')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
