# Generated by Django 6.0.3 on 2026-03-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_shift_closing_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaulttransaction',
            name='vault',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vaulttransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='BranchVault',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='VaultTransaction',
        ),
    ]
