# Generated by Django 6.0.3 on 2026-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_branchvault_vaulttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_at_time',
            field=models.FloatField(default=0.0),
        ),
    ]
