# Generated by Django 6.0.3 on 2026-03-23 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productunit'),
        ('sales', '0007_orderitem_cost_at_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_quantity', models.PositiveIntegerField(default=1)),
                ('promo_type', models.CharField(choices=[('discount', 'Discounted Price'), ('freebie', 'Free Product Bonus')], default='discount', max_length=20)),
                ('promo_price', models.FloatField(blank=True, null=True)),
                ('bonus_qty', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('bonus_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_promos', to='inventory.product')),
                ('trigger_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='inventory.product')),
            ],
        ),
    ]
