# Generated by Django 6.0.3 on 2026-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_orderitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(default=1500.0),
        ),
    ]
