# Generated by Django 6.0.3 on 2026-03-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_payrolldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='variance_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
