# Generated by Django 6.0.3 on 2026-03-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_phase_3_2_variance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockauditlog',
            name='log_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('adjust', 'Adjust'), ('void', 'Void'), ('transfer', 'Transfer'), ('recount', 'Recount')], default='adjust', max_length=20),
        ),
        migrations.AddField(
            model_name='stockauditlog',
            name='qty_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockauditlog',
            name='qty_before',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('running_balance', models.FloatField(default=0.0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('due', 'Due'), ('deducted', 'Deducted')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='sales.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order')),
            ],
        ),
    ]
